import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-surety-bond-claim-indemnity-recovery",
  "engine": "recovery",
  "title": "Surety Bond Claim & Indemnity Recovery",
  "shortTitle": "Surety Bond Claim and Indemnity Recovery",
  "tagline": "Maximize indemnity, collateral, salvage, and subrogation recoveries after surety claim payments.",
  "industry": "Surety Financial Operations",
  "buyer": "Surety carriers and claims administrators",
  "uiPort": 4666,
  "apiPort": 5666,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Surety Bond Claim & Indemnity Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases in one accountable workflow. Maximize indemnity, collateral, salvage, and subrogation recoveries after surety claim payments.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Surety Bond Claim & Indemnity Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("bond-indemnity-library","SBC01","Bond indemnity library","Execute bond indemnity library using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed bond indemnity library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Bond indemnity library Reference","text","SBC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("principal-indemnitor-registry","SBC02","Principal indemnitor registry","Execute principal indemnitor registry using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed principal indemnitor registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Principal indemnitor registry Reference","text","SBC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("claim-payment-ingestion","SBC03","Claim payment ingestion","Execute claim payment ingestion using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed claim payment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Claim payment ingestion Reference","text","SBC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("completion-cost-validation","SBC04","Completion cost validation","Execute completion cost validation using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed completion cost validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Completion cost validation Reference","text","SBC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("loss-adjustment-expense","SBC05","Loss adjustment expense","Execute loss adjustment expense using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed loss adjustment expense decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Loss adjustment expense Reference","text","SBC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("collateral-inventory","SBC06","Collateral inventory","Execute collateral inventory using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed collateral inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Collateral inventory Reference","text","SBC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("collateral-drawdown","SBC07","Collateral drawdown","Execute collateral drawdown using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed collateral drawdown decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Collateral drawdown Reference","text","SBC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("salvage-asset-tracking","SBC08","Salvage asset tracking","Execute salvage asset tracking using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed salvage asset tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Salvage asset tracking Reference","text","SBC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("principal-reimbursement-demand","SBC09","Principal reimbursement demand","Execute principal reimbursement demand using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed principal reimbursement demand decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Principal reimbursement demand Reference","text","SBC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("co-surety-allocation","SBC10","Co-surety allocation","Execute co-surety allocation using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed co-surety allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Co-surety allocation Reference","text","SBC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("subrogation-opportunity","SBC11","Subrogation opportunity","Execute subrogation opportunity using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed subrogation opportunity decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Subrogation opportunity Reference","text","SBC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("recovery-litigation-workflow","SBC12","Recovery litigation workflow","Execute recovery litigation workflow using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed recovery litigation workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Recovery litigation workflow Reference","text","SBC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("cash-recovery-ledger","SBC13","Cash recovery ledger","Execute cash recovery ledger using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed cash recovery ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Cash recovery ledger Reference","text","SBC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("reserve-reconciliation","SBC14","Reserve reconciliation","Execute reserve reconciliation using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed reserve reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Reserve reconciliation Reference","text","SBC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]}),
feature("bond-principal-analytics","SBC15","Bond principal analytics","Execute bond principal analytics using bond forms, indemnity agreements, claims, completion costs, salvage, collateral, principal assets, subrogation, recoveries, and releases.","Produce a governed bond principal analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Bond / Principal Account","text","Bond / Principal Account · Standard Case"],["caseReference","Bond principal analytics Reference","text","SBC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",823750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",996738],["domainDriver","Bond Type","select","Contract",["Contract","Commercial","Court"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Bond indemnity library case","Principal indemnitor registry case","Claim payment ingestion case","Completion cost validation case","Loss adjustment expense case"]})
]);
